# Site settings
# Enter your own credentials here
title: "The Blog"
email: lizzyro@gmail.com
description: >
  Tell us about your site
baseurl: "" # replace ``/research-pages`` with the name of the parents repository
url: "lizzyro.github.io" # replate ``Materials-Informatics-Lab`` with your Github username
github_username:  lizzyro
disqus: lizzyro

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5
